# Generated by Django 5.0.6 on 2024-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_info',
            field=models.TextField(),
        ),
    ]
