# Generated by Django 5.0.6 on 2024-08-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_products_options_alter_products_prod_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slider_photo', models.ImageField(upload_to='media/slider')),
            ],
        ),
    ]
