# Generated by Django 5.0.6 on 2024-08-10 11:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
