# Generated by Django 5.0.6 on 2024-07-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='photo',
            field=models.ImageField(upload_to='media/vendor/'),
        ),
    ]
