# Generated by Django 5.0.6 on 2024-07-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='media/prod_imgs/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unit')),
            ],
        ),
    ]
