# Generated by Django 5.0.6 on 2024-07-31 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': '6.Inventory'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '3.Product'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': '4.Purchase'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': '5.Sale'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': '2.Unit'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': '1.Vendor'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='price',
            new_name='total_bal_qty',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='pur_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_amt',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='vendor',
        ),
        migrations.AddField(
            model_name='inventory',
            name='pur_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.sale'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sale_qty',
            field=models.FloatField(default=0),
        ),
    ]
