# Generated by Django 5.0.6 on 2024-08-01 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='pur_qty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sale'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale_qty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amt',
            field=models.FloatField(default=0),
        ),
    ]
